; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
; platform = espressif32
platform = espressif32@5.3.0
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio


build_flags = 
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=5

; change MCU frequency
board_build.f_cpu = 160000000L

board_build.partitions = partition.csv

; board_build.partitions = max_app_4MB.csv
; board_build.partitions = min_spiffs.csv
; board_build.partitions = default.csv ; или имя вашего файла с разметкой
monitor_speed = 115200
; monitor_filters = 
	; esp32_exception_decoder
	; time      ; добавляет время получения сообщения
	; colorize  ; подсвечивает логи (ошибки красным)
build_type = debug ; добавляет больше отладочной информации в бинарник

board_build.filesystem = littlefs
lib_deps = 
	gyverlibs/GyverPortal@^3.6.6
  bblanchon/ArduinoJson
;   https://github.com/Bodmer/JPEGDecoder.git
;   https://github.com/Bodmer/TFT_eFEX.git
;   Plotter
lib_ldf_mode = deep